# Generated by Django 5.1.3 on 2024-11-23 16:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountVarification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('verification_method', models.CharField(choices=[('nid', 'NID'), ('birth certificate', 'Birth Certificate'), ('driving licence', 'Driving Licence'), ('passport', 'Passport'), ('green card', 'Green Card')], max_length=200, null=True)),
                ('date_of_birth', models.CharField(max_length=10, null=True)),
                ('ocopation_status', models.CharField(choices=[('job', 'Job'), ('freelancer', 'Freelancer')], max_length=10, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True)),
                ('freelancing_marketplace_url', models.URLField(blank=True, null=True)),
                ('status', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
