# Generated by Django 5.1.3 on 2024-11-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_accountvarification'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountvarification',
            name='id_no',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
