# Generated by Django 5.1.3 on 2024-11-23 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_accountvarification_profile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountvarification',
            old_name='User',
            new_name='user',
        ),
    ]
