# Generated by Django 5.1.3 on 2024-12-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_accountvarification_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountvarification',
            old_name='status',
            new_name='accept',
        ),
        migrations.AddField(
            model_name='accountvarification',
            name='decline',
            field=models.BooleanField(default=False),
        ),
    ]
